<a href="https://colab.research.google.com/github/Ayo-Agboola/Python_Data_cleaning-_and_wrangling/blob/main/week1_Data_Inspection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

Load Datasets

In [ ]:
import pandas as pd
df = pd.read_csv("SLU Opportunity Wise Data.csv")

View Dataset

In [ ]:
df.head()

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,6/14/2023 12:30,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,6/29/2024 18:52,Faria,1/12/2001,Female,Pakistan,Nwihs,Radiology,3/11/2024 12:01,Started,1080,6/14/2023 12:36,11/3/2022 18:30
1,5/1/2023 5:29,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,6/29/2024 18:52,Poojitha,8/16/2000,Female,India,SAINT LOUIS,Information Systems,3/11/2024 12:01,Started,1080,5/1/2023 6:08,11/3/2022 18:30
2,4/9/2023 20:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,6/29/2024 18:52,Emmanuel,1/27/2002,Male,United States,Illinois Institute of Technology,Computer Science,3/11/2024 12:01,Started,1080,05/11/2023 1085640:21:29,11/3/2022 18:30
3,8/29/2023 5:20,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,6/29/2024 18:52,Amrutha Varshini,11/1/1999,Female,United States,Saint Louis University,Information Systems,3/11/2024 12:01,Team Allocated,1070,10/9/2023 22:02,11/3/2022 18:30
4,1/6/2023 15:26,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,6/29/2024 18:52,Vinay Varshith,4/19/2000,Male,United States,Saint Louis University,Computer Science,3/11/2024 12:01,Started,1080,1/6/2023 15:40,11/3/2022 18:30

In [ ]:
df.tail(10)

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
8548,45350.01325,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Kofi,10/26/1990,Male,Ghana,College of Health and Well-Being Kintampo,Medical Laboratory Science,3/11/2024 12:03,Team Allocated,1070,45350.03431,3/8/2024 14:00
8549,4/30/2023 18:22,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Subhash Chandra,5/12/2001,Male,India,Vishnu Institute of Technology,Information Systems,3/11/2024 12:03,Team Allocated,1070,2/12/2024 20:57,3/8/2024 14:00
8550,12/27/2023 23:52,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Saikrishna,1/18/1999,Male,United States,Saint Louis university,Information Systems,3/11/2024 12:03,Team Allocated,1070,3/8/2024 7:25,3/8/2024 14:00
8551,7/9/2023 6:53,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Lalith Adithya Reddy,9/17/2000,Male,United States,Saint Louis University,Computer Science,3/11/2024 12:03,Applied,1010,2/9/2024 16:57,NaN
8552,1/6/2024 17:04,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Kaustubh,7/6/2003,Male,India,P. V. G Nashik,Artificial Intelligence and Data Science,3/11/2024 12:03,Team Allocated,1070,2/12/2024 3:01,3/8/2024 14:00
8553,3/5/2024 16:39,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Selam,10/14/2006,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,3/11/2024 12:03,Team Allocated,1070,3/5/2024 17:10,3/8/2024 14:00
8554,3/6/2024 15:58,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Gowri Sailesh,5/18/1999,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,3/11/2024 12:03,Team Allocated,1070,3/6/2024 18:22,3/8/2024 14:00
8555,2/29/2024 15:02,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Abiola,3/16/1999,Male,Nigeria,Tai Solarin university of Education,Political Science,3/11/2024 12:03,Team Allocated,1070,2/29/2024 15:10,3/8/2024 14:00
8556,12/23/2023 3:53,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,venumadhavi,6/5/1997,Female,United States,Saint Louis University,Information Systems,3/11/2024 12:03,Team Allocated,1070,2/27/2024 6:48,3/8/2024 14:00
8557,6/1/2023 13:22,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,3/8/2024 11:30,Prashanth Reddy,11/30/2000,Male,India,Saint Louis University,Artificial Intelligence,3/11/2024 12:03,Team Allocated,1070,2/16/2024 16:33,3/8/2024 14:00

Dataset Shape

In [ ]:
df.shape

(8558, 16)

Column names

In [ ]:
df.columns

Index(['Learner SignUp DateTime', 'Opportunity Id', 'Opportunity Name',
       'Opportunity Category', 'Opportunity End Date', 'First Name',
       'Date of Birth', 'Gender', 'Country', 'Institution Name',
       'Current/Intended Major', 'Entry created at', 'Status Description',
       'Status Code', 'Apply Date', 'Opportunity Start Date'],
      dtype='object')

Data types

In [ ]:
df.dtypes

Learner SignUp DateTime    object
Opportunity Id             object
Opportunity Name           object
Opportunity Category       object
Opportunity End Date       object
First Name                 object
Date of Birth              object
Gender                     object
Country                    object
Institution Name           object
Current/Intended Major     object
Entry created at           object
Status Description         object
Status Code                 int64
Apply Date                 object
Opportunity Start Date     object
dtype: object

Columns

In [ ]:
df.columns

Index(['learner_signup_datetime', 'opportunity_id', 'opportunity_name',
       'opportunity_category', 'opportunity_end_date', 'first_name',
       'date_of_birth', 'gender', 'country', 'institution_name',
       'current/intended_major', 'entry_created_at', 'status_description',
       'status_code', 'apply_date', 'opportunity_start_date'],
      dtype='object')

Rename columns

In [ ]:
from os import replace
df.columns = (
    df.columns
    .str.strip()
        .str.lower()
            .str.replace(" ", "_")
        )

Date Related Columns

In [ ]:
date_columns = [
    "learner_signup_datetime",
    "opportunity_end_date",
    "date_of_birth",
    "entry_created_at",
    "apply_date",
    "opportunity_start_date"
]
date_columns

['learner_signup_datetime',
 'opportunity_end_date',
 'date_of_birth',
 'entry_created_at',
 'apply_date',
 'opportunity_start_date']

Raw values

In [ ]:
list(df.columns)

['learner_signup_datetime',
 'opportunity_id',
 'opportunity_name',
 'opportunity_category',
 'opportunity_end_date',
 'first_name',
 'date_of_birth',
 'gender',
 'country',
 'institution_name',
 'current/intended_major',
 'entry_created_at',
 'status_description',
 'status_code',
 'apply_date',
 'opportunity_start_date']

In [ ]:
df[date_columns].head(10)

,learner_signup_datetime,opportunity_end_date,date_of_birth,entry_created_at,apply_date,opportunity_start_date
0,6/14/2023 12:30,6/29/2024 18:52,1/12/2001,3/11/2024 12:01,6/14/2023 12:36,11/3/2022 18:30
1,5/1/2023 5:29,6/29/2024 18:52,8/16/2000,3/11/2024 12:01,5/1/2023 6:08,11/3/2022 18:30
2,4/9/2023 20:35,6/29/2024 18:52,1/27/2002,3/11/2024 12:01,05/11/2023 1085640:21:29,11/3/2022 18:30
3,8/29/2023 5:20,6/29/2024 18:52,11/1/1999,3/11/2024 12:01,10/9/2023 22:02,11/3/2022 18:30
4,1/6/2023 15:26,6/29/2024 18:52,4/19/2000,3/11/2024 12:01,1/6/2023 15:40,11/3/2022 18:30
5,3/2/2024 19:16,6/29/2024 18:52,5/12/1996,3/11/2024 12:01,3/2/2024 20:30,NaN
6,5/31/2023 7:11,6/29/2024 18:52,9/9/2001,3/11/2024 12:01,6/14/2023 5:29,11/3/2022 18:30
7,7/22/2023 7:30,6/29/2024 18:52,2/27/2006,3/11/2024 12:01,7/22/2023 7:44,11/3/2022 18:30
8,3/20/2023 16:36,6/29/2024 18:52,12/22/2005,3/11/2024 12:01,5/24/2023 13:44,11/3/2022 18:30
9,5/11/2023 3:40,6/29/2024 18:52,6/26/1998,3/11/2024 12:01,12/17/2023 2:58,11/3/2022 18:30

Check missing values in date columns

In [ ]:
df[date_columns].isna().sum()

learner_signup_datetime       0
opportunity_end_date          0
date_of_birth                 0
entry_created_at              0
apply_date                    0
opportunity_start_date     3794
dtype: int64

Raw values inspection

In [ ]:
df["learner_signup_datetime"].head(20)

0      6/14/2023 12:30
1        5/1/2023 5:29
2       4/9/2023 20:35
3       8/29/2023 5:20
4       1/6/2023 15:26
5       3/2/2024 19:16
6       5/31/2023 7:11
7       7/22/2023 7:30
8      3/20/2023 16:36
9       5/11/2023 3:40
10      9/4/2023 20:08
11     1/28/2023 21:56
12     8/18/2023 23:49
13     6/14/2023 17:51
14      1/5/2023 16:33
15     3/16/2023 12:11
16    10/31/2023 22:20
17       8/8/2023 7:12
18      8/15/2023 9:41
19     3/29/2023 23:08
Name: learner_signup_datetime, dtype: object

Check values

In [ ]:
df["learner_signup_datetime"].apply(type).value_counts()

learner_signup_datetime
<class 'str'>    8558
Name: count, dtype: int64

Convert to datetime

In [ ]:
df["learner_signup_datetime"] = pd.to_datetime(df["learner_signup_datetime"], errors="coerce")

Verify result

In [ ]:
df["learner_signup_datetime"].dtype

dtype('<M8[ns]')

Check failed conversion

In [ ]:
df["learner_signup_datetime"].isna().sum()

np.int64(295)

Raw values

In [ ]:
df["opportunity_end_date"].head(20)

0     6/29/2024 18:52
1     6/29/2024 18:52
2     6/29/2024 18:52
3     6/29/2024 18:52
4     6/29/2024 18:52
5     6/29/2024 18:52
6     6/29/2024 18:52
7     6/29/2024 18:52
8     6/29/2024 18:52
9     6/29/2024 18:52
10    6/29/2024 18:52
11    6/29/2024 18:52
12    6/29/2024 18:52
13    6/29/2024 18:52
14    6/29/2024 18:52
15    6/29/2024 18:52
16    6/29/2024 18:52
17    6/29/2024 18:52
18    6/29/2024 18:52
19    6/29/2024 18:52
Name: opportunity_end_date, dtype: object

Convert to datetime

In [ ]:
df["opportunity_end_date"] = pd.to_datetime(df["opportunity_end_date"], errors="coerce")

In [ ]:
df['opportunity_end_date'].dtype
df['opportunity_end_date'].isna().sum()

np.int64(1262)

Raw values

In [ ]:
df["date_of_birth"].head(20)

0      1/12/2001
1      8/16/2000
2      1/27/2002
3      11/1/1999
4      4/19/2000
5      5/12/1996
6       9/9/2001
7      2/27/2006
8     12/22/2005
9      6/26/1998
10     10/1/1998
11     6/30/1997
12      9/9/1998
13      5/6/1997
14     8/22/1998
15     4/12/2004
16     7/28/2006
17      9/4/1999
18    11/15/2001
19     4/20/1994
Name: date_of_birth, dtype: object

Convert to datetime

In [ ]:
df["date_of_birth"] = pd.to_datetime(df["date_of_birth"], errors="coerce")

Verify conversion

In [ ]:
df["date_of_birth"].dtype
df["date_of_birth"].isna().sum()

np.int64(0)

Raw values

In [ ]:
df["entry_created_at"].head(20)

0     3/11/2024 12:01
1     3/11/2024 12:01
2     3/11/2024 12:01
3     3/11/2024 12:01
4     3/11/2024 12:01
5     3/11/2024 12:01
6     3/11/2024 12:01
7     3/11/2024 12:01
8     3/11/2024 12:01
9     3/11/2024 12:01
10    3/11/2024 12:01
11    3/11/2024 12:01
12    3/11/2024 12:01
13    3/11/2024 12:01
14    3/11/2024 12:01
15    3/11/2024 12:01
16    3/11/2024 12:01
17    3/11/2024 12:01
18    3/11/2024 12:01
19    3/11/2024 12:01
Name: entry_created_at, dtype: object

Convert to datetime

In [ ]:
df["entry_created_at"] = pd.to_datetime(df['entry_created_at'], errors="coerce")

In [ ]:
df["entry_created_at"].dtype
df["entry_created_at"].isna().sum()

np.int64(0)

In [ ]:
df["apply_date"].head(20)

0              6/14/2023 12:36
1                5/1/2023 6:08
2     05/11/2023 1085640:21:29
3              10/9/2023 22:02
4               1/6/2023 15:40
5               3/2/2024 20:30
6               6/14/2023 5:29
7               7/22/2023 7:44
8              5/24/2023 13:44
9              12/17/2023 2:58
10              9/4/2023 21:02
11             1/30/2023 23:10
12             1/24/2024 18:57
13             6/14/2023 18:04
14             11/10/2022 6:54
15              4/2/2023 18:18
16            10/31/2023 22:24
17               8/8/2023 7:23
18              9/1/2023 10:12
19             3/29/2023 23:22
Name: apply_date, dtype: object

To check data type

In [ ]:
df["apply_date"].apply(type).value_counts()

apply_date
<class 'str'>    8558
Name: count, dtype: int64

In [ ]:
df["apply_date"].dtype
df["apply_date"].isna().sum()

np.int64(0)

In [ ]:
numeric_mask = df["apply_date"].str.fullmatch(r"\d+")
numeric_mask.value_counts()

apply_date
False    8558
Name: count, dtype: int64

Convert dates

In [ ]:
df.loc[numeric_mask,"apply_date"] = pd.to_datetime(df.loc[numeric_mask, "apply_date"].astype(float), unit="D", origin="1899-12-30")

Convert column

In [ ]:
df["apply_date"] = pd.to_datetime(df["apply_date"], errors="coerce")

Verify result

In [ ]:
df["apply_date"].dtype

dtype('<M8[ns]')

In [ ]:
df["apply_date"].isna().sum()

np.int64(307)

In [ ]:
df["apply_date"].head(20)

0    2023-06-14 12:36:00
1    2023-05-01 06:08:00
2                    NaT
3    2023-10-09 22:02:00
4    2023-01-06 15:40:00
5    2024-03-02 20:30:00
6    2023-06-14 05:29:00
7    2023-07-22 07:44:00
8    2023-05-24 13:44:00
9    2023-12-17 02:58:00
10   2023-09-04 21:02:00
11   2023-01-30 23:10:00
12   2024-01-24 18:57:00
13   2023-06-14 18:04:00
14   2022-11-10 06:54:00
15   2023-04-02 18:18:00
16   2023-10-31 22:24:00
17   2023-08-08 07:23:00
18   2023-09-01 10:12:00
19   2023-03-29 23:22:00
Name: apply_date, dtype: datetime64[ns]

In [ ]:
df["opportunity_start_date"].head(20)

0     11/3/2022 18:30
1     11/3/2022 18:30
2     11/3/2022 18:30
3     11/3/2022 18:30
4     11/3/2022 18:30
5                 NaN
6     11/3/2022 18:30
7     11/3/2022 18:30
8     11/3/2022 18:30
9     11/3/2022 18:30
10    11/3/2022 18:30
11    11/3/2022 18:30
12    11/3/2022 18:30
13    11/3/2022 18:30
14    11/3/2022 18:30
15    11/3/2022 18:30
16    11/3/2022 18:30
17    11/3/2022 18:30
18    11/3/2022 18:30
19    11/3/2022 18:30
Name: opportunity_start_date, dtype: object

In [ ]:
df["opportunity_start_date"].isna().sum()

np.int64(4637)

In [ ]:
df["opportunity_start_date"] = pd.to_datetime(df["opportunity_start_date"], errors="coerce")

In [ ]:
df["opportunity_start_date"].dtype

dtype('<M8[ns]')

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import pandas as pd
df = pd.read_csv("SLU Opportunity Wise Data.csv")

In [ ]:
df.columns

Index(['learner_signup_datetime', 'opportunity_id', 'opportunity_name',
       'opportunity_category', 'opportunity_end_date', 'first_name',
       'date_of_birth', 'gender', 'country', 'institution_name',
       'current/intended_major', 'entry_created_at', 'status_description',
       'status_code', 'apply_date', 'opportunity_start_date'],
      dtype='object')

Age Column

In [ ]:
df["age_of_learner"] = (
    (pd.Timestamp("today") - df["date_of_birth"])
    .dt.days // 365

)

Validate

In [ ]:
df["age_of_learner"].describe()

count    8558.000000
mean       25.821921
std         4.382423
min         6.000000
25%        24.000000
50%        25.000000
75%        27.000000
max        59.000000
Name: age_of_learner, dtype: float64

In [ ]:
df["age_of_learner"].isna().sum()

np.int64(0)

Engagement Duration

In [ ]:
df["engagement_duration_days"] = (df["opportunity_start_date"] -
df["apply_date"]).dt.days

In [ ]:
df['engagement_duration_days'].describe()

count    3802.000000
mean      -77.497633
std       175.685833
min      -476.000000
25%      -224.000000
50%       -12.000000
75%        33.000000
max       322.000000
Name: engagement_duration_days, dtype: float64

In [ ]:
df["engagement_duration_days"].isna().sum()

np.int64(4756)

Flag column

In [ ]:
df["negative_engagement_flag"] = df["engagement_duration_days"] < 0

In [ ]:
df["negative_engagement_flag"].value_counts()

negative_engagement_flag
False    6519
True     2039
Name: count, dtype: int64